const USER_LOGIN = 'USER_LOGIN';
const USER_SIGNUP = 'USER_SIGNUP';
const USER_VERIRIFICATION = 'USER_VERIRIFICATION';
const CLEAR_LOGIN_STATE = 'CLEAR_LOGIN_STATE';
const RESEND_VERIRIFICATION = 'RESEND_VERIRIFICATION';
const ADMIN_USER_LOGIN = 'ADMIN_USER_LOGIN';
const GET_ALL_USERS = 'GET_ALL_USERS';

export {
  USER_LOGIN,
  USER_SIGNUP,
  USER_VERIRIFICATION,
  RESEND_VERIRIFICATION,
  ADMIN_USER_LOGIN,
  CLEAR_LOGIN_STATE,
  GET_ALL_USERS,
};
