const USER_LOGIN = 'USER_LOGIN';
const USER_SIGNUP = 'USER_SIGNUP';
const USER_VERIRIFICATION = 'USER_VERIRIFICATION';
const RESEND_VERIRIFICATION = 'RESEND_VERIRIFICATION';
const ADMIN_USER_LOGIN = 'ADMIN_USER_LOGIN';

export {
  USER_LOGIN,
  USER_SIGNUP,
  USER_VERIRIFICATION,
  RESEND_VERIRIFICATION,
  ADMIN_USER_LOGIN,
};
